### PR TITLE
add properties for line color and character height

### PR DESCRIPTION
**Pull request by autonomobil**
- add properties for line color
- add property for character height
- adjust ID position to center of lanelet
- rename some stuff

### CODE REVIEW

**Comment by autonomobil** [comment]
lanelet_rviz_plugin_color

**Comment by m-naumann** [comment]
Hi Moritz, thanks for the MR! I'll only have time to have a closer look in June, hope that's okay.

**Comment by m-naumann** [comment]
It's merged now with some small changes, thanks again

**Comment by autonomobil** [comment]
no problem, thank you too!

**Pull request merged**
